packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/passkey': 1.7.6
  '@better-auth/redis-storage': 1.7.6
  '@better-auth/utils': 0.4.2
  better-auth: 1.7.6
  typescript: 5.9.3

overrides:
  '@better-auth/utils': 0.4.2
