// Icon data map — pure data, no React, no "use client".
// Importing this from a server component is safe because it's just arrays.
import {
  DashboardBrowsingIcon,
  UserGroupIcon,
  Wallet01Icon,
  MoneyReceive01Icon,
  Settings01Icon,
  BellIcon,
  Logout01Icon,
  Search01Icon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronsUpDown,
  Add01Icon,
  Cancel01Icon,
  Tick01Icon,
  ViewIcon,
  EyeOffIcon,
  UserIcon,
  Building01Icon,
  Mail01Icon,
  SmartPhone01Icon,
  CreditCardIcon,
  LockKeyholeIcon,
  Shield01Icon,
  Calendar01Icon,
  CalendarDaysIcon,
  CalendarClockIcon,
  FilterHorizontalIcon,
  ListFilterIcon,
  Download04Icon,
  Upload04Icon,
  Refresh01Icon,
  TrendingUpIcon,
  Alert01Icon,
  AlertTriangle,
  Delete01Icon,
  PencilEdit01Icon,
  Camera01Icon,
  Loading03Icon,
  LoaderCircleIcon,
  CircleIcon,
  BadgeDollarSignIcon,
  File01Icon,
  Copy01Icon,
  InformationCircleIcon,
  MoreHorizontalIcon,
  BrushCleaningIcon,
  BadgeInfoIcon,
  MapPinIcon,
  Message01Icon,
  LayoutPanelLeftIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowDownToLineIcon,
  BadgeCheckIcon,
  ShieldAlertIcon,
  CheckCircle,
  FileSpreadsheetIcon,
  Sun01Icon,
  Moon01Icon,
  MonitorIcon,
  MinusSignIcon,
  CheckCheckIcon,
  ArrowUpRight01Icon,
  PercentCircleIcon,
  CustomerSupportIcon,
  VolumeHighIcon,
  ComputerIcon,
  VolumeOffIcon,
  ManagerIcon,
  SlidersHorizontalIcon,
  UserCircleIcon,
  FingerPrintIcon,
  PasswordValidationIcon,
  Megaphone01Icon,
  PinIcon,
  PinOffIcon,
  SparklesIcon,
  BookOpen01Icon,
  Idea01Icon,
  Rocket01Icon,
  AnalyticsUpIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  SentIcon,
  StopIcon,
  Clock01Icon,
  InboxIcon,
  ArrowDown01Icon,
  Menu01Icon,
} from "@hugeicons/core-free-icons";

export type IconData = typeof BellIcon;

export const icons: Record<string, IconData> = {
  // Navigation & sidebar
  dashboard: DashboardBrowsingIcon,
  customers: UserGroupIcon,
  accountOfficers: ManagerIcon,
  loans: Wallet01Icon,
  repayments: MoneyReceive01Icon,
  settings: Settings01Icon,
  notifications: BellIcon,
  logout: Logout01Icon,
  support: CustomerSupportIcon,
  sound: VolumeHighIcon,
  soundOff: VolumeOffIcon,
  popup: ComputerIcon,
  sliders: SlidersHorizontalIcon,
  userCircle: UserCircleIcon,
  fingerprint: FingerPrintIcon,
  password: PasswordValidationIcon,

  // Common actions
  search: Search01Icon,
  plus: Add01Icon,
  x: Cancel01Icon,
  check: Tick01Icon,
  edit: PencilEdit01Icon,
  delete: Delete01Icon,
  copy: Copy01Icon,
  download: Download04Icon,
  upload: Upload04Icon,
  refresh: Refresh01Icon,
  filter: FilterHorizontalIcon,
  listFilter: ListFilterIcon,
  view: ViewIcon,

  // Navigation chevrons
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  chevronsUpDown: ChevronsUpDown,
  arrowLeft: ArrowLeft01Icon,
  arrowRight: ArrowRight01Icon,

  // Status & feedback
  alert: Alert01Icon,
  alertTriangle: AlertTriangle,
  shieldAlert: ShieldAlertIcon,
  info: InformationCircleIcon,
  badgeInfo: BadgeInfoIcon,
  checkCircle: CheckCircle,
  badgeCheck: BadgeCheckIcon,
  checkCheck: CheckCheckIcon,
  loader: Loading03Icon,
  loaderCircle: LoaderCircleIcon,

  // User & people
  user: UserIcon,
  userGroup: UserGroupIcon,
  phone: SmartPhone01Icon,
  mail: Mail01Icon,
  message: Message01Icon,
  mapPin: MapPinIcon,

  // Finance & business
  creditCard: CreditCardIcon,
  dollarSign: BadgeDollarSignIcon,
  wallet: Wallet01Icon,
  moneyReceive: MoneyReceive01Icon,
  building: Building01Icon,

  // Security
  lock: LockKeyholeIcon,
  shield: Shield01Icon,
  eyeOff: EyeOffIcon,

  // Date & time
  calendar: Calendar01Icon,
  calendarDays: CalendarDaysIcon,
  calendarClock: CalendarClockIcon,

  // Files & documents
  file: File01Icon,
  fileSpreadsheet: FileSpreadsheetIcon,

  // Theme
  sun: Sun01Icon,
  moon: Moon01Icon,
  monitor: MonitorIcon,

  // Misc
  camera: Camera01Icon,
  trendingUp: TrendingUpIcon,
  moreHorizontal: MoreHorizontalIcon,
  brushCleaning: BrushCleaningIcon,
  circle: CircleIcon,
  minus: MinusSignIcon,
  panelLeft: LayoutPanelLeftIcon,
  menu: Menu01Icon,
  arrowDownToLine: ArrowDownToLineIcon,
  arrowUpRight: ArrowUpRight01Icon,
  percent: PercentCircleIcon,
  // Callouts
  callouts: Megaphone01Icon,
  pin: PinIcon,
  pinOff: PinOffIcon,
  sparkles: SparklesIcon,
  book: BookOpen01Icon,
  idea: Idea01Icon,
  rocket: Rocket01Icon,
  analytics: AnalyticsUpIcon,
  // Chat support
  thumbsUp: ThumbsUpIcon,
  thumbsDown: ThumbsDownIcon,
  send: SentIcon,
  stop: StopIcon,
  history: Clock01Icon,
  inbox: InboxIcon,
  arrowDown: ArrowDown01Icon,
};
