-- v2: better-auth tables (generated by the better-auth CLI) and the v2 ledger rules.
-- Generated with `prisma migrate diff` from the init schema, then edited so that
-- "User" becomes better-auth's "user" in place: rows, and the foreign keys that
-- point at them, survive instead of being dropped and recreated.

-- CreateEnum
CREATE TYPE "CommodityRequestStatus" AS ENUM ('IN_REVIEW', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "TenureChangeReason" AS ENUM ('DEFAULT', 'TOPUP', 'LIQUIDATION', 'ADMIN');

-- CreateEnum
CREATE TYPE "TenureChangeStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- AlterEnum
ALTER TYPE "MicroLoanStatus" ADD VALUE 'APPROVED';

-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('LOAN_APPROVED', 'LOAN_REJECTED', 'LOAN_DISBURSED', 'TOPUP_APPROVED', 'TOPUP_REJECTED', 'TOPUP_DISBURSED', 'PENALTY_APPLIED', 'TENURE_CHANGE_PROPOSED', 'TENURE_CHANGE_APPROVED', 'TENURE_CHANGE_REJECTED', 'PAYMENT_INFLOW_APPROVED', 'PAYMENT_INFLOW_REJECTED', 'VARIATION_SUBMITTED', 'PERIOD_CLOSED', 'COMMODITY_APPROVED', 'COMMODITY_REJECTED', 'CUSTOMER_STATUS_CHANGED', 'ADMIN_INVITED', 'ADMIN_REMOVED', 'PAYROLL_UPLOADED');
ALTER TABLE "AuditLog" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "AuditAction_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "AuditEntityType_new" AS ENUM ('LOAN', 'MICRO_LOAN', 'TENURE_CHANGE', 'PAYMENT_INFLOW', 'PAYROLL_PERIOD', 'COMMODITY_LOAN', 'USER', 'PAYROLL_UPLOAD');
ALTER TABLE "AuditLog" ALTER COLUMN "entityType" TYPE "AuditEntityType_new" USING ("entityType"::text::"AuditEntityType_new");
ALTER TYPE "AuditEntityType" RENAME TO "AuditEntityType_old";
ALTER TYPE "AuditEntityType_new" RENAME TO "AuditEntityType";
DROP TYPE "AuditEntityType_old";
COMMIT;

-- RenameTable: "User" -> better-auth's "user". Foreign keys follow the table.
ALTER TABLE "User" RENAME TO "user";
ALTER TABLE "user" RENAME CONSTRAINT "User_pkey" TO "user_pkey";
ALTER INDEX "User_email_key" RENAME TO "user_email_key";

-- AlterTable: passwords move to better-auth's "account" (Stage 8 migrates v1 users);
-- avatar is better-auth's image; email is required (placeholders for phone-only users).
ALTER TABLE "user" RENAME COLUMN "avatar" TO "image";
ALTER TABLE "user" DROP COLUMN "contact",
DROP COLUMN "password",
ADD COLUMN     "emailVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "phoneNumber" TEXT,
ADD COLUMN     "phoneNumberVerified" BOOLEAN,
ADD COLUMN     "twoFactorEnabled" BOOLEAN DEFAULT false,
ALTER COLUMN "email" SET NOT NULL,
ALTER COLUMN "type" SET DEFAULT 'CUSTOMER',
ALTER COLUMN "status" SET DEFAULT 'FLAGGED';

-- DropForeignKey
ALTER TABLE "TenureExtension" DROP CONSTRAINT "TenureExtension_loanId_fkey";

-- DropForeignKey
ALTER TABLE "TenureExtension" DROP CONSTRAINT "TenureExtension_requestedById_fkey";

-- AlterTable
ALTER TABLE "CommodityLoan" ADD COLUMN     "microLoanId" TEXT,
ADD COLUMN     "status" "CommodityRequestStatus" NOT NULL DEFAULT 'IN_REVIEW';

-- AlterTable
ALTER TABLE "Deduction" ADD COLUMN     "penalizedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PayrollPeriod" ADD COLUMN     "variationFilePath" TEXT;

-- AlterTable
ALTER TABLE "PaymentInflow" ADD COLUMN     "proofPath" TEXT;

-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "maxDeductionRate" DECIMAL(5,4),
ALTER COLUMN "interestRate" DROP NOT NULL,
ALTER COLUMN "managementFeeRate" DROP NOT NULL,
ALTER COLUMN "penaltyRate" DROP NOT NULL;

-- DropTable
DROP TABLE "TenureExtension";

-- DropEnum
DROP TYPE "ExtensionStatus";

-- CreateTable
CREATE TABLE "TenureChange" (
    "id" TEXT NOT NULL,
    "loanId" TEXT NOT NULL,
    "previousTenure" INTEGER NOT NULL,
    "monthsDelta" INTEGER NOT NULL,
    "reason" "TenureChangeReason" NOT NULL,
    "status" "TenureChangeStatus" NOT NULL DEFAULT 'PENDING',
    "microLoanId" TEXT,
    "requestedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TenureChange_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account" (
    "id" TEXT NOT NULL,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP(3),
    "refreshTokenExpiresAt" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification" (
    "id" TEXT NOT NULL,
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "twoFactor" (
    "id" TEXT NOT NULL,
    "secret" TEXT NOT NULL,
    "backupCodes" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "verified" BOOLEAN DEFAULT true,
    "failedVerificationCount" INTEGER DEFAULT 0,
    "lockedUntil" TIMESTAMP(3),

    CONSTRAINT "twoFactor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passkey" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "publicKey" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "credentialID" TEXT NOT NULL,
    "counter" INTEGER NOT NULL,
    "deviceType" TEXT NOT NULL,
    "backedUp" BOOLEAN NOT NULL,
    "transports" TEXT,
    "createdAt" TIMESTAMP(3),
    "aaguid" TEXT,

    CONSTRAINT "passkey_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "user_phoneNumber_key" ON "user"("phoneNumber");

-- CreateIndex
CREATE UNIQUE INDEX "TenureChange_microLoanId_key" ON "TenureChange"("microLoanId");

-- CreateIndex
CREATE INDEX "TenureChange_loanId_idx" ON "TenureChange"("loanId");

-- CreateIndex
CREATE INDEX "session_userId_idx" ON "session"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "session_token_key" ON "session"("token");

-- CreateIndex
CREATE INDEX "account_userId_idx" ON "account"("userId");

-- CreateIndex
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");

-- CreateIndex
CREATE INDEX "twoFactor_secret_idx" ON "twoFactor"("secret");

-- CreateIndex
CREATE INDEX "twoFactor_userId_idx" ON "twoFactor"("userId");

-- CreateIndex
CREATE INDEX "passkey_userId_idx" ON "passkey"("userId");

-- CreateIndex
CREATE INDEX "passkey_credentialID_idx" ON "passkey"("credentialID");

-- CreateIndex
CREATE UNIQUE INDEX "CommodityLoan_microLoanId_key" ON "CommodityLoan"("microLoanId");

-- AddForeignKey
ALTER TABLE "CommodityLoan" ADD CONSTRAINT "CommodityLoan_microLoanId_fkey" FOREIGN KEY ("microLoanId") REFERENCES "MicroLoan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TenureChange" ADD CONSTRAINT "TenureChange_loanId_fkey" FOREIGN KEY ("loanId") REFERENCES "Loan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TenureChange" ADD CONSTRAINT "TenureChange_microLoanId_fkey" FOREIGN KEY ("microLoanId") REFERENCES "MicroLoan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TenureChange" ADD CONSTRAINT "TenureChange_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "Admin"("userId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "twoFactor" ADD CONSTRAINT "twoFactor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "passkey" ADD CONSTRAINT "passkey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
