import { Heading, Text } from '@react-email/components';
import * as React from 'react';
import { EmailLayout, h1, text } from './shared';

interface RepaymentScheduleEmailProps {
  month: string;
  totalCustomers?: number;
  totalAmount?: string;
  variationId?: string;
  draft?: boolean;
  /** Who generated (submitted) it, for the copy every super admin receives. */
  submittedBy?: string;
}

export const RepaymentScheduleEmail = ({
  month,
  totalCustomers,
  totalAmount,
  variationId,
  draft,
  submittedBy,
}: RepaymentScheduleEmailProps) => {
  const title = `${draft ? 'DRAFT' : 'Generated'} Payroll Variation – ${month}`;
  return (
    <EmailLayout
      preview={title}
      footerNote="This is an automated message, please do not reply."
    >
      <Heading style={h1}>{title}</Heading>
      <Text style={text}>Hi,</Text>
      <Text style={text}>
        Attached are the changed payroll deductions for {month}. Unchanged
        customers are omitted.
      </Text>

      {totalCustomers !== undefined && totalAmount !== undefined && (
        <Text style={text}>
          <strong>Details:</strong>
          <br />- Schedule Period: {month}
          <br />- Total Customers: {totalCustomers}
          <br />- Deductions in this variation: {totalAmount}
        </Text>
      )}

      <Text style={text}>
        {variationId ? `Variation ${variationId}. ` : ''}
        {draft
          ? 'This draft is for review only: do not send it to payroll. When it is right, submit the variation in MicroBuilt and send payroll the file it saves.'
          : `This is the variation ${submittedBy ? `${submittedBy} generated` : 'generated'} in MicroBuilt for ${month}: send it to payroll as it is. If it was generated by mistake, a super admin can revert it from the variation dialog before payroll money comes in for the month.`}
      </Text>

      <Text style={{ ...text, marginBottom: 0 }}>
        Best regards,
        <br />
        MicroBuilt Loan Operations
      </Text>
    </EmailLayout>
  );
};
