"use client";

import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { isAxiosError } from "axios";
import { Icon, icons } from "@/components/icon";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  dialogBodyClass,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { useUserProvider } from "@/store/auth";
import {
  requestVariationSchedule,
  revertVariationSchedule,
  submitVariationSchedule,
} from "@/lib/mutations/admin/repayments";
import {
  getVariationFile,
  getVariationPreview,
  suggestEmailCorrection,
  variationPreviewKey,
  type VariationAction,
  type VariationPeriod,
} from "@/lib/payroll/variations";
import { cn, formatCurrency } from "@/lib/utils";
import { MonthPicker } from "./month-picker";
import {
  VariationRows,
  VariationRowsSkeleton,
  actionHints,
  actionLabels,
  actionTone,
} from "./variation-rows";

const errorMessage = (error: unknown) => {
  const message = isAxiosError(error)
    ? error.response?.data?.message
    : error instanceof Error
      ? error.message
      : null;
  return Array.isArray(message)
    ? message.join(". ")
    : typeof message === "string"
      ? message
      : "Could not complete this request. Please retry.";
};

const currentMonth = () => {
  const parts = new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "2-digit",
    timeZone: "Africa/Lagos",
  }).formatToParts(new Date());
  const get = (type: string) => parts.find((p) => p.type === type)!.value;
  return `${get("year")}-${get("month")}`;
};

const formatDay = (value: string) =>
  new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Africa/Lagos",
  }).format(new Date(value));

type Stage = "idle" | "confirm-generate" | "revert-reason" | "revert-code";

/** Where the month stands, with what to do next. Generated months carry the way back. */
function StatusBanner({
  period,
  canRevert,
  onRevert,
}: {
  period: VariationPeriod;
  canRevert: boolean;
  onRevert: () => void;
}) {
  if (period.closedAt)
    return (
      <div className="flex items-start gap-3 rounded-xl border bg-muted/40 p-3.5">
        <Icon icon={icons.lock} size={18} className="mt-0.5 shrink-0 text-muted-foreground" />
        <div className="min-w-0 text-sm">
          <p className="font-medium">{period.label} is closed</p>
          <p className="text-muted-foreground">
            Payroll results are final for this month. The file stays available below.
          </p>
        </div>
      </div>
    );
  if (period.submittedAt)
    return (
      <div className="rounded-xl border border-success/25 bg-success/8 p-3.5">
        <div className="flex items-start gap-3">
          <Icon icon={icons.checkCircle} size={18} className="mt-0.5 shrink-0 text-success" />
          <div className="min-w-0 flex-1 text-sm">
            <p className="font-medium">Generated {formatDay(period.submittedAt)}</p>
            <p className="text-muted-foreground">
              Deductions are frozen at these amounts. Send payroll the file below.
            </p>
          </div>
        </div>
        {(canRevert || period.revertBlockedBy) && (
          <div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-success/20 pt-3 text-xs">
            <span className="text-muted-foreground">
              {canRevert
                ? "Generated by mistake? A super admin can undo it before payroll money comes in."
                : `Can't be reverted: ${period.revertBlockedBy}.`}
            </span>
            {canRevert && (
              <Button
                type="button"
                size="sm"
                variant="ghost"
                className="h-7 px-2 text-destructive hover:bg-destructive/10 hover:text-destructive"
                onClick={onRevert}
              >
                <Icon icon={icons.refresh} size={14} />
                Revert
              </Button>
            )}
          </div>
        )}
      </div>
    );
  return (
    <div className="flex items-start gap-3 rounded-xl border border-warning/25 bg-warning/8 p-3.5">
      <Icon icon={icons.calendarClock} size={18} className="mt-0.5 shrink-0 text-warning" />
      <div className="min-w-0 text-sm">
        <p className="font-medium">Not generated yet</p>
        <p className="text-muted-foreground">
          Review the changes and email yourself a draft. Generating freezes the deductions and opens next month.
        </p>
      </div>
    </div>
  );
}

export default function RequestVariationSchedule({
  role,
  defaultOpen = false,
}: {
  role: "ADMIN" | "SUPER_ADMIN";
  defaultOpen?: boolean;
}) {
  const superAdmin = role === "SUPER_ADMIN";
  const { user } = useUserProvider();
  const [open, setOpen] = useState(defaultOpen);
  const [month, setMonth] = useState(currentMonth);
  const [viewYear, setViewYear] = useState(() => Number(currentMonth().slice(0, 4)));
  const [action, setAction] = useState<VariationAction | "ALL">("ALL");
  // Defaulting to the signed-in admin avoids hand-typing an address whose
  // typos only surface later as a silent bounce.
  const [typedEmail, setTypedEmail] = useState<string | null>(null);
  const email = typedEmail ?? user?.email ?? "";
  const suggestion = suggestEmailCorrection(email);
  const [stage, setStage] = useState<Stage>("idle");
  const [acknowledged, setAcknowledged] = useState(false);
  const [reason, setReason] = useState("");
  const [code, setCode] = useState("");
  const [error, setError] = useState("");

  const actionFilter = action === "ALL" ? undefined : action;
  const preview = useQuery({
    queryKey: variationPreviewKey(month, { action: actionFilter }),
    queryFn: () => getVariationPreview(month, { action: actionFilter }),
    enabled: open && Boolean(month),
    retry: 1,
  });
  const generation = useMutation(requestVariationSchedule);
  const submission = useMutation(submitVariationSchedule);
  const reversal = useMutation(revertVariationSchedule);
  const download = useMutation({ mutationFn: getVariationFile });
  const busy = generation.isPending || submission.isPending || download.isPending || reversal.isPending;

  const data = preview.data;
  const period = data?.period;
  const submitted = Boolean(period?.submittedAt);
  const closed = Boolean(period?.closedAt);
  const canRevert = superAdmin && submitted && !closed && !period?.revertBlockedBy;
  const total = data?.counts ? data.counts.START + data.counts.AMEND + data.counts.STOP : 0;
  const shownAmount = data?.rows.reduce((sum, row) => sum + (row.action === "STOP" ? 0 : row.amount), 0) ?? 0;

  function resetTransient() {
    setStage("idle");
    setAcknowledged(false);
    setReason("");
    setCode("");
    setError("");
  }

  function changeMonth(next: string) {
    setMonth(next);
    resetTransient();
  }

  async function run(work: () => Promise<unknown>, after?: () => void) {
    setError("");
    try {
      await work();
      after?.();
    } catch (failure) {
      setError(errorMessage(failure));
    }
  }

  const sendDraft = () =>
    run(() => generation.mutateAsync({ period: month, email: email.trim() || undefined }));
  const generate = () => run(() => submission.mutateAsync({ period: month }), resetTransient);
  // A wrong code clears the boxes so the next one can be typed straight in.
  const revert = (otp = code) =>
    run(() => reversal.mutateAsync({ period: month, reason: reason.trim(), code: otp }), resetTransient).then(() =>
      setCode(""),
    );
  const downloadFile = () =>
    run(async () => {
      try {
        const file = await download.mutateAsync(month);
        window.open(file.url, "_blank", "noopener,noreferrer");
      } catch (failure) {
        toast.error("Could not open the file");
        throw failure;
      }
    });

  const shownError = error || (preview.isError ? errorMessage(preview.error) : "");

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        setOpen(next);
        if (!next) resetTransient();
      }}
    >
      <DialogTrigger asChild>
        <Button
          size="sm"
          variant="outline"
          className="h-10 w-full border-destructive/40 bg-card px-4 font-normal text-brand hover:bg-destructive/5 sm:w-auto"
        >
          <Icon icon={icons.fileSpreadsheet} size={16} />
          Schedule Variation
        </Button>
      </DialogTrigger>
      <DialogContent className="grid-cols-1 gap-0 sm:max-w-2xl">
        <DialogHeader className="border-b">
          <div className="flex items-center gap-3">
            <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">
              <Icon icon={icons.fileSpreadsheet} size={20} />
            </span>
            <div className="min-w-0 text-left">
              <DialogTitle>Payroll variation</DialogTitle>
              <DialogDescription>What payroll must start, change or stop deducting for a month.</DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className={cn(dialogBodyClass, "min-w-0 pt-4")}>
          <div className="grid gap-1.5 sm:max-w-xs">
            <Label className="text-xs text-muted-foreground">Payroll month</Label>
            <MonthPicker value={month} onChange={changeMonth} viewYear={viewYear} onViewYearChange={setViewYear} />
          </div>

          {shownError && (
            <p
              role="alert"
              className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive"
            >
              {shownError}
            </p>
          )}

          {period ? (
            <StatusBanner
              period={period}
              canRevert={canRevert && stage === "idle"}
              onRevert={() => {
                setError("");
                setStage("revert-reason");
              }}
            />
          ) : (
            <Skeleton className="h-[72px] w-full rounded-xl" />
          )}

          {(stage === "revert-reason" || stage === "revert-code") && period && (
            <section
              aria-label="Revert the variation"
              className="grid gap-3 rounded-xl border border-destructive/30 bg-destructive/5 p-4"
            >
              <div className="flex items-start gap-3">
                <Icon icon={icons.shieldAlert} size={18} className="mt-0.5 shrink-0 text-destructive" />
                <div className="text-sm">
                  <p className="font-medium">Revert {period.label}</p>
                  <p className="text-muted-foreground">
                    The month goes back to not generated, its deductions reopen, next month&apos;s are removed and
                    the file is deleted. Every super admin is told. Only do this if the file never reached payroll.
                  </p>
                </div>
              </div>

              {stage === "revert-reason" ? (
                <form
                  className="grid gap-3"
                  onSubmit={(e) => {
                    e.preventDefault();
                    if (reason.trim().length >= 5) setStage("revert-code");
                  }}
                >
                  <div className="grid gap-1.5">
                    <Label htmlFor="revert-reason">Why are you reverting it?</Label>
                    <Input
                      id="revert-reason"
                      autoFocus
                      value={reason}
                      onChange={(e) => setReason(e.target.value)}
                      placeholder="Generated instead of requesting a draft"
                      maxLength={300}
                      className="bg-card"
                    />
                  </div>
                  <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                    <Button type="button" variant="outline" onClick={resetTransient}>
                      Cancel
                    </Button>
                    <Button type="submit" variant="destructive" disabled={reason.trim().length < 5}>
                      Continue
                    </Button>
                  </div>
                </form>
              ) : (
                <form
                  className="grid gap-3"
                  onSubmit={(e) => {
                    e.preventDefault();
                    if (code.length === 6) void revert();
                  }}
                >
                  <div className="grid gap-2">
                    <Label htmlFor="revert-code">Enter the code from your authenticator app</Label>
                    <InputOTP
                      id="revert-code"
                      autoFocus
                      maxLength={6}
                      inputMode="numeric"
                      pattern="^[0-9]*$"
                      autoComplete="one-time-code"
                      value={code}
                      onChange={(v) => setCode(v.replace(/\D/g, ""))}
                      onComplete={(v: string) => void revert(v)}
                      disabled={reversal.isPending}
                    >
                      <InputOTPGroup className="gap-2">
                        {Array.from({ length: 6 }, (_, i) => (
                          <InputOTPSlot key={i} index={i} className="size-11 rounded-md border bg-card text-lg" />
                        ))}
                      </InputOTPGroup>
                    </InputOTP>
                    <p className="text-xs text-muted-foreground">Reason: {reason.trim()}</p>
                  </div>
                  <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end">
                    <Button type="button" variant="outline" disabled={busy} onClick={() => setStage("revert-reason")}>
                      Back
                    </Button>
                    <Button type="submit" variant="destructive" disabled={busy || code.length !== 6}>
                      {reversal.isPending ? "Reverting…" : "Revert variation"}
                    </Button>
                  </div>
                </form>
              )}
            </section>
          )}

          <section aria-label="Changes" className="grid gap-3">
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4" role="group" aria-label="Filter by action">
              {(["ALL", "START", "AMEND", "STOP"] as const).map((key) => {
                const active = action === key;
                const count = key === "ALL" ? total : data?.counts[key];
                return (
                  <button
                    key={key}
                    type="button"
                    aria-pressed={active}
                    onClick={() => setAction(key)}
                    className={cn(
                      "rounded-xl border p-3 text-left transition-colors",
                      active ? "border-primary bg-primary/5 ring-1 ring-primary" : "hover:bg-muted/50",
                    )}
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span
                        className={cn(
                          "rounded-md px-1.5 py-0.5 text-[11px] font-medium",
                          key === "ALL" ? "bg-muted text-muted-foreground" : actionTone[key],
                        )}
                      >
                        {key === "ALL" ? "All" : actionLabels[key]}
                      </span>
                      {data ? (
                        <span className="text-lg font-semibold tabular-nums">{count}</span>
                      ) : (
                        <Skeleton className="h-6 w-6" />
                      )}
                    </div>
                    <p className="mt-1.5 truncate text-xs text-muted-foreground">
                      {key === "ALL" ? "Every change" : actionHints[key]}
                    </p>
                  </button>
                );
              })}
            </div>

            <div className="flex items-baseline justify-between gap-2 text-xs text-muted-foreground">
              <span>{data ? `${data.rows.length} ${data.rows.length === 1 ? "loan" : "loans"}` : "Loading…"}</span>
              {data && data.rows.length > 0 && (
                <span>
                  Monthly deductions:{" "}
                  <span className="font-semibold text-foreground tabular-nums">{formatCurrency(shownAmount)}</span>
                </span>
              )}
            </div>
            {preview.isLoading ? <VariationRowsSkeleton /> : data ? <VariationRows rows={data.rows} /> : null}
          </section>

          {data && !submitted && !closed && (
            <section aria-label="Email a draft" className="grid gap-2 rounded-xl border bg-muted/30 p-4">
              <div>
                <p className="text-sm font-medium">Email a draft for review</p>
                <p className="text-xs text-muted-foreground">
                  The draft is for checking only. Nothing is frozen or sent to payroll.
                </p>
              </div>
              <div className="flex flex-col gap-2 sm:flex-row">
                <Input
                  id="variation-email"
                  type="email"
                  autoComplete="email"
                  aria-label="Email the draft to"
                  value={email}
                  onChange={(e) => setTypedEmail(e.target.value)}
                  className="bg-card"
                />
                <Button
                  type="button"
                  variant="outline"
                  className="bg-card"
                  disabled={busy || !email.trim()}
                  onClick={sendDraft}
                >
                  <Icon icon={icons.mail} size={16} />
                  {generation.isPending ? "Sending…" : "Send draft"}
                </Button>
              </div>
              {suggestion && (
                <p className="text-xs text-warning">
                  Did you mean{" "}
                  <button type="button" className="font-medium underline" onClick={() => setTypedEmail(suggestion)}>
                    {suggestion}
                  </button>
                  ?
                </p>
              )}
            </section>
          )}

          {superAdmin && data && !submitted && !closed && stage === "confirm-generate" && (
            <section
              aria-label="Confirm"
              className="grid gap-3 rounded-xl border border-warning/30 bg-warning/8 p-4 text-sm"
            >
              <p>
                Generating {data.period.label} freezes these deductions, opens next month and emails the file to every
                super admin to send to payroll. Months are generated in order.
              </p>
              <div className="flex items-start gap-2">
                <Checkbox
                  id="variation-ack"
                  checked={acknowledged}
                  onCheckedChange={(v) => setAcknowledged(v === true)}
                />
                <Label htmlFor="variation-ack" className="font-normal">
                  I have reviewed the {total} {total === 1 ? "change" : "changes"} for {data.period.label}.
                </Label>
              </div>
            </section>
          )}

          <DialogFooter className="border-t pt-4">
            {submitted ? (
              <Button type="button" disabled={busy || !period?.hasFile} onClick={downloadFile}>
                <Icon icon={icons.download} size={16} />
                {download.isPending ? "Opening…" : "Download file"}
              </Button>
            ) : closed || !superAdmin ? null : stage === "confirm-generate" ? (
              <>
                <Button type="button" variant="outline" disabled={busy} onClick={resetTransient}>
                  Cancel
                </Button>
                <Button type="button" disabled={!acknowledged || busy} onClick={generate}>
                  {submission.isPending ? "Generating…" : "Generate variation"}
                </Button>
              </>
            ) : (
              <Button
                type="button"
                disabled={busy || !data || stage !== "idle"}
                onClick={() => {
                  setError("");
                  setStage("confirm-generate");
                }}
              >
                <Icon icon={icons.fileSpreadsheet} size={16} />
                Generate variation
              </Button>
            )}
          </DialogFooter>
        </div>
      </DialogContent>
    </Dialog>
  );
}
